universe                = docker
docker_image            = alabijesujoba/zmm-tts:v2
executable              = /data/users/jalabi/Internship_NII/Data/scripts/download/asr/preprocess_fleurs2.sh
initialdir              = /data/users/jalabi/Internship_NII/Data/scripts/download/asr/
output                  = /data/users/jalabi/Internship_NII/Data/scripts/download/asr/logs/res22.$(ClusterId).$(ProcId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).out
error                   = /data/users/jalabi/Internship_NII/Data/scripts/download/asr/logs/res22.$(ClusterId).$(ProcId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).err
log                     = /data/users/jalabi/Internship_NII/Data/scripts/download/asr/logs/res22.$(ClusterId).$(ProcId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).out
request_GPUs = 0
request_CPUs = 2
request_memory = 15G
requirements = (GPUs_GlobalMemoryMb >= 5000) && (machine == "cl18lx.lsv.uni-saarland.de")
queue
