################################
# Model: language identification with ECAPA
# Authors: Tanel Alumäe, 2021
# ################################

# Basic parameters
seed: 1988
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_url: /data/users/jalabi/Internship_NII/speechbrain/recipes/VoxLingua107/lang_id_fleur
output_folder: !ref <output_url>/results-lid/method1/wav2vec2-xlsr-300m/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
# data_folder: !PLACEHOLDER

shards_url: /data/users/jalabi/Internship_NII/speechbrain/recipes/VoxLingua107/lang_id_fleur/data
train_meta: !ref <shards_url>/train/meta.json
val_meta: !ref <shards_url>/dev/meta.json
train_shards: !ref <shards_url>/train/shard-{000000..000020}.tar
val_shards: !ref <shards_url>/dev/shard-{000000..000002}.tar

# Set to directory on a large disk if you are training on Webdataset shards hosted on the web
shard_cache_dir:

wav2vec2_hub: facebook/wav2vec2-xls-r-300m
wav2vec2_folder: !ref <save_folder>/wav2vec2_checkpoint

ckpt_interval_minutes: 5


####################### Training Parameters ####################################
number_of_epochs: 5
sample_rate: 16000
sentence_len: 3 # seconds
batch_size: 64
batch_size_val: 8
lr: 0.0001
lr_wav2vec2: 0.00001

#freeze all wav2vec2
freeze_wav2vec2: False
#set to true to freeze the CONV part of the wav2vec2 model
# We see an improvement of 2% with freezing CNNs
freeze_wav2vec2_conv: False

####################### Model Parameters #######################################
encoder_dim: 1024

# Number of emotions
out_n_neurons: 24 # (anger, happiness, sadness, neutral)

# dataloader_options:
#    batch_size: !ref <batch_size>
#    shuffle: True
#    num_workers: 2  # 2 on linux but 0 works on windows
#    drop_last: False

train_dataloader_options:
    num_workers: 2
    batch_size: !ref <batch_size>

val_dataloader_options:
    num_workers: 2
    batch_size: !ref <batch_size_val>

# Wav2vec2 encoder
wav2vec2: !new:speechbrain.lobes.models.huggingface_transformers.wav2vec2.Wav2Vec2
    source: !ref <wav2vec2_hub>
    output_norm: True
    freeze: !ref <freeze_wav2vec2>
    freeze_feature_extractor: !ref <freeze_wav2vec2_conv>
    save_path: !ref <wav2vec2_folder>

avg_pool: !new:speechbrain.nnet.pooling.StatisticsPooling
    return_std: False

output_mlp: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <encoder_dim>
    n_neurons: !ref <out_n_neurons>
    bias: False

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

modules:
    wav2vec2: !ref <wav2vec2>
    output_mlp: !ref <output_mlp>

model: !new:torch.nn.ModuleList
    - [!ref <output_mlp>]

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

compute_cost: !name:speechbrain.nnet.losses.nll_loss

error_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.classification_error
        reduction: batch

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

wav2vec2_opt_class: !name:torch.optim.Adam
    lr: !ref <lr_wav2vec2>

lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: 0.0025
    annealing_factor: 0.9
    patient: 0

lr_annealing_wav2vec2: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr_wav2vec2>
    improvement_threshold: 0.0025
    annealing_factor: 0.9

# Logging + checkpoints
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

# error_stats: !name:speechbrain.utils.metric_stats.MetricStats
#    metric: !name:speechbrain.nnet.losses.classification_error
#        reduction: batch

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        wav2vec2: !ref <wav2vec2>
        lr_annealing_output: !ref <lr_annealing>
        lr_annealing_wav2vec2: !ref <lr_annealing_wav2vec2>
        counter: !ref <epoch_counter>
